const searchForm = document.getElementById('search-form');
const searchResults = document.getElementById('table-body');

searchForm.addEventListener('submit', function(event) {
  event.preventDefault();

  const searchTerm = document.getElementById('search').value;

  // Simulate a database query
  const results = [
    { name: 'John Doe', ident: 001, email: 'johndoe@gmail.com'},
    { name: 'Bob Crypto', ident: 002, email: 'bobdecrypts@gmail.com' },
    { name: 'Sarah Smith', ident: 004, email: 'sarahsmith@gmail.com' },
    { name: 'Ryan Carter', ident: 005, email: 'ryancarter@yahoo.com' },
    { name: 'David Lee', ident: 006, email: 'davidlee@hotmail.com' },
    { name: 'Jennifer Kim', ident: 007, email: 'jenniferkim@gmail.com' },
    { name: 'Tyler Adams', ident: 008, email: 'tyleradams@gmail.com' },
    { name: 'Emma Davis', ident: 009, email: 'emmadavis@yahoo.com' },
    { name: 'Jacob Brown', ident: 010, email: 'jacobbrown@gmail.com' },
    { name: 'Avery Johnson', ident: 011, email: 'averyjohnson@hotmail.com' },
    { name: 'Ella Wilson', ident: 012, email: 'ellawilson@gmail.com' },
    { name: 'Lucas Rodriguez', ident: 013, email: 'lucasrodriguez@yahoo.com' },
    { name: 'Madison Moore', ident: 014, email: 'madisonmoore@gmail.com' },
    { name: 'Noah Hernandez', ident: 015, email: 'noahernandez@hotmail.com' },
    { name: 'Isabella Wilson', ident: 016, email: 'isabellawilson@gmail.com' },
    { name: 'Ethan Martinez', ident: 017, email: 'ethanmartinez@yahoo.com' },
    { name: 'Mia Taylor', ident: 018, email: 'miataylor@gmail.com' },
    { name: 'Alexander King', ident: 019, email: 'alexanderking@hotmail.com' },
    { name: 'Avery Mitchell', ident: 020, email: 'averymitchell@gmail.com' },
    { name: 'William Scott', ident: 021, email: 'williamscott@yahoo.com' },
    { name: 'Charlotte Parker', ident: 022, email: 'charlotteparker@gmail.com' },
    { name: 'Oliver Evans', ident: 023, email: 'oliverevans@hotmail.com' },
    { name: 'Sophia Young', ident: 024, email: 'sophiayoung@gmail.com' },
    { name: 'Michael Green', ident: 025, email: 'michaelgreen@yahoo.com' },
    { name: 'Emma Adams', ident: 026, email: 'emmaadams@gmail.com' },
    { name: 'Benjamin Wright', ident: 027, email: 'benjaminwright@hotmail.com' },
    { name: 'Grace Turner', ident: 028, email: 'graceturner@gmail.com' },
    { name: 'Daniel Lee', ident: 029, email: 'daniellee@yahoo.com' },
    { name: 'Avery Garcia', ident: 030, email: 'averygarcia@gmail.com' },
    { name: 'Liam Adams', ident: 031, email: 'liamadams@hotmail.com' },
    { name: 'Aria Hernandez', ident: 032, email: 'ariahernandez@gmail.com' },
    { name: 'Lucas White', ident: 033, email: 'lucaswhite@yahoo.com' },
    { name: 'Chloe Parker', ident: 034, email: 'chloeparker@gmail.com' },
    { name: 'Frank Johnson', ident: 036, email: 'frankjohnson@gmail.com' },
    { name: 'Gina Lee', ident: 037, email: 'ginalee@hotmail.com' },
    { name: 'Henry Park', ident: 038, email: 'henrypark@gmail.com' },
    { name: 'Ivy Wu', ident: 039, email: 'ivywu@yahoo.com' },
    { name: 'Jack Brown', ident: 040, email: 'jackbrown@gmail.com' },
    { name: 'Katie Wong', ident: 041, email: 'katiewong@hotmail.com' },
    { name: 'Larry Chen', ident: 042, email: 'larrychen@gmail.com' },
    { name: 'Mia Kim', ident: 043, email: 'miakim@yahoo.com' },
    { name: 'Nate Patel', ident: 044, email: 'natepatel@gmail.com' },
    { name: 'Oliver Green', ident: 045, email: 'olivergreen@hotmail.com' },
    { name: 'Peter Nguyen', ident: 046, email: 'peternguyen@gmail.com' },
    { name: 'Qian Li', ident: 047, email: 'qianli@yahoo.com' },
    { name: 'Rachel Rodriguez', ident: 048, email: 'rachelrodriguez@gmail.com' },
    { name: 'Steve Davis', ident: 049, email: 'stevedavis@hotmail.com' },
    { name: 'Tina Chen', ident: 050, email: 'tinachen@gmail.com' },
    { name: 'Ursula Gonzalez', ident: 051, email: 'ursulagonzalez@yahoo.com' },
    { name: 'Victor Torres', ident: 052, email: 'victortorres@gmail.com' },
    { name: 'Wendy Chen', ident: 053, email: 'wendychen@hotmail.com' },
    { name: 'Xavier Ramirez', ident: 054, email: 'xavierramirez@gmail.com' },
    { name: 'Yoko Kato', ident: 055, email: 'yokokato@yahoo.com' },
    { name: 'Zoe Chen', ident: 056, email: 'zoechen@gmail.com' },
    { name: 'Arthur Lee', ident: 057, email: 'arthurlee@hotmail.com' },
    { name: 'Betty Brown', ident: 058, email: 'bettybrown@gmail.com' },
    { name: 'Carl Kim', ident: 059, email: 'carlkim@yahoo.com' },
    { name: 'Diane Patel', ident: 060, email: 'dianepatel@gmail.com' },
    { name: 'Ethan Chen', ident: 061, email: 'ethanchen@hotmail.com' },
    { name: 'Felicia Davis', ident: 062, email: 'feliciadavis@gmail.com' },
    { name: 'Graham Johnson', ident: 063, email: 'grahamjohnson@yahoo.com' },
    { name: 'Haley Park', ident: 064, email: 'haleypark@gmail.com' },
    { name: 'Isabella Wu', ident: 065, email: 'isabellawu@hotmail.com' },
    { name: 'Nina Patel', ident: 066, email: 'ninapatel@gmail.com'},
    { name: 'Samantha Turner', ident: 067, email: 'samanthaturner@gmail.com'},
    { name: 'Oliver Wood', ident: 068, email: 'oliverwood@yahoo.com'},
    { name: 'Rebecca Brown', ident: 069, email: 'rebeccabrown@gmail.com'},
    { name: 'Jeremy Lee', ident: 070, email: 'jeremylee@hotmail.com'},
    { name: 'Eliza Davis', ident: 071, email: 'elizadavis@gmail.com'},
    { name: 'Cameron Nguyen', ident: 072, email: 'cameronnguyen@yahoo.com'},
    { name: 'Avery Hernandez', ident: 073, email: 'averyhernandez@gmail.com'},
    { name: 'Justin Kim', ident: 074, email: 'justinkim@hotmail.com'},
    { name: 'Madeline Jackson', ident: 075, email: 'madelinejackson@gmail.com'},
    { name: 'Mia Adams', ident: 076, email: 'miaadams@yahoo.com'},
    { name: 'Gavin Lewis', ident: 077, email: 'gavinlewis@gmail.com'},
    { name: 'Lauren Lee', ident: 078, email: 'laurenlee@hotmail.com'},
    { name: 'Eliana Scott', ident: 079, email: 'elianascott@gmail.com'},
    { name: 'Olivia Taylor', ident: 080, email: 'oliviataylor@yahoo.com'},
    { name: 'Adam Carter', ident: 081, email: 'adamcarter@gmail.com'},
    { name: 'Victoria Smith', ident: 082, email: 'victoriasmith@hotmail.com'},
    { name: 'Grace Wilson', ident: 083, email: 'gracewilson@gmail.com'},
    { name: 'Jackson Patel', ident: 084, email: 'jacksonpatel@yahoo.com'},
    { name: 'Sophia Green', ident: 085, email: 'sophiagreen@gmail.com'},
    { name: 'William Lee', ident: 086, email: 'williamlee@hotmail.com'},
    { name: 'Abigail Nguyen', ident: 087, email: 'abigailnguyen@gmail.com'},
    { name: 'Aiden Hernandez', ident: 088, email: 'aidenhernandez@yahoo.com'},
    { name: 'Audrey Kim', ident: 089, email: 'audreykim@gmail.com'},
    { name: 'Ethan Jackson', ident: 090, email: 'ethanjackson@yahoo.com'},
    { name: 'Emma Adams', ident: 091, email: 'emmaadams@gmail.com'},
    { name: 'Benjamin Lewis', ident: 092, email: 'benjaminlewis@hotmail.com'},
    { name: 'Lily Lee', ident: 093, email: 'lilylee@gmail.com'},
    { name: 'Nicholas Scott', ident: 094, email: 'nicholasscott@yahoo.com'},
    { name: 'Isabella Taylor', ident: 095, email: 'isabellataylor@gmail.com'},
    { name: 'Emily Flores', ident: 096, email: 'emily.flores@gmail.com' },
    { name: 'Nina Patel', ident: 097, email: 'ninapatel@yahoo.com' },
    { name: 'Gregory Scott', ident: 098, email: 'gregscott@gmail.com' },
    { name: 'Diane Nguyen', ident: 099, email: 'dnguyen@gmail.com' },
    { name: 'Jasmine Li', ident: 100, email: 'jli@outlook.com' },
    { name: 'Edward Chen', ident: 101, email: 'chen.edward@gmail.com' },
    { name: 'Jennifer Lee', ident: 102, email: 'jlee@yahoo.com' },
    { name: 'Samantha Smith', ident: 103, email: 'ssmith@hotmail.com' },
    { name: 'William Kim', ident: 104, email: 'wkim@gmail.com' },
    { name: 'Lauren Brown', ident: 105, email: 'lbrown@hotmail.com' },
    { name: 'Patrick Garcia', ident: 106, email: 'pgarcia@gmail.com' },
    { name: 'Victoria Davis', ident: 107, email: 'vdavis@yahoo.com' },
    { name: 'Miles Cooper', ident: 108, email: 'mcooper@gmail.com' },
    { name: 'Diana Torres', ident: 109, email: 'dtorres@gmail.com' },
    { name: 'Erica Jackson', ident: 110, email: 'ejackson@yahoo.com' },
    { name: 'Oliver Hernandez', ident: 111, email: 'ohernandez@gmail.com' },
    { name: 'Sophie Nguyen', ident: 112, email: 'snguyen@yahoo.com' },
    { name: 'James Robinson', ident: 113, email: 'jrobinson@gmail.com' },
    { name: 'Karen Patel', ident: 114, email: 'kpatel@hotmail.com' },
    { name: 'Rachel Kim', ident: 115, email: 'rkim@gmail.com' },
    { name: 'Anthony Baker', ident: 116, email: 'abaker@yahoo.com' },
    { name: 'Isabella Reed', ident: 117, email: 'ireed@gmail.com' },
    { name: 'David Turner', ident: 118, email: 'dturner@yahoo.com' },
    { name: 'Rebecca Hill', ident: 119, email: 'rhill@gmail.com' },
    { name: 'Mark Johnson', ident: 120, email: 'mjohnson@yahoo.com' },
    { name: 'Sarah Brown', ident: 121, email: 'sbrown@gmail.com' },
    { name: 'Christopher Anderson', ident: 122, email: 'canderson@yahoo.com' },
    { name: 'Maria Rodriguez', ident: 123, email: 'mrodriguez@gmail.com' },
    { name: 'Andrew Hernandez', ident: 124, email: 'ahernandez@yahoo.com' },
    { name: 'Emma Davis', ident: 125, email: 'edavis@gmail.com' },
    { name: 'Kevin Lee', ident: 126, email: 'klee@yahoo.com' },
    { name: 'James Corden', ident: 127, email: 'jamescorden@yahoo.com' },
    { name: 'Ella Green', ident: 128, email: 'ellagreen@hotmail.com' },
    { name: 'Isaac Wood', ident: 129, email: 'isaacwood@gmail.com' },
    { name: 'Lily Stone', ident: 130, email: 'lilystone@yahoo.com' },
    { name: 'Oliver West', ident: 131, email: 'oliverwest@gmail.com' },
    { name: 'Mia Hill', ident: 132, email: 'miahill@hotmail.com' },
    { name: 'Levi Jones', ident: 133, email: 'levijones@gmail.com' },
    { name: 'Sophia Black', ident: 134, email: 'sophiablack@yahoo.com' },
    { name: 'Lucas White', ident: 135, email: 'lucaswhite@hotmail.com' },
    { name: 'Evelyn King', ident: 136, email: 'evelynking@gmail.com' },
    { name: 'Alexander Knight', ident: 137, email: 'alexanderknight@yahoo.com' },
    { name: 'Emily Green', ident: 138, email: 'emilygreen@gmail.com' },
    { name: 'Jacob Bishop', ident: 139, email: 'jacobbishop@hotmail.com' },
    { name: 'Ava Cole', ident: 140, email: 'avacole@gmail.com' },
    { name: 'Benjamin Cross', ident: 141, email: 'benjamincross@yahoo.com' },
    { name: 'Avery Campbell', ident: 142, email: 'averycampbell@hotmail.com' },
    { name: 'William Mitchell', ident: 143, email: 'williammitchell@gmail.com' },
    { name: 'Chloe Bell', ident: 144, email: 'chloebell@yahoo.com' },
    { name: 'Ethan Sullivan', ident: 145, email: 'ethansullivan@gmail.com' },
    { name: 'Victoria Spencer', ident: 146, email: 'victoriaspencer@hotmail.com' },
    { name: 'Henry Fisher', ident: 147, email: 'henryfisher@yahoo.com' },
    { name: 'Sofia Cooper', ident: 148, email: 'sofiacooper@gmail.com' },
    { name: 'Carter Nelson', ident: 149, email: 'carternelson@hotmail.com' },
    { name: 'Scarlett Murphy', ident: 150, email: 'scarlettmurphy@yahoo.com' },
    { name: 'Sebastian Gray', ident: 151, email: 'sebastiangray@gmail.com' },
    { name: 'Avery Henderson', ident: 152, email: 'averyhenderson@yahoo.com' },
    { name: 'John Scott', ident: 153, email: 'js13@gmail.com' },
    { name: 'Carter Allen', ident: 154, email: 'carterallen@hotmail.com' },
    { name: 'Scarlett White', ident: 155, email: 'scarlettwhite@yahoo.com' },
    { name: 'Sebastian Brown', ident: 156, email: 'sebastianbrown@gmail.com' },
    { name: 'Nina Smith', ident: 157, email: 'nina_smith@yahoo.com' },
    { name: 'Oliver Martinez', ident: 158, email: 'omartinez@gmail.com' },
    { name: 'Sophia Lee', ident: 159, email: 'sophialee@hotmail.com' },
    { name: 'Henry Kim', ident: 160, email: 'henrykim@gmail.com' },
    { name: 'Samantha Park', ident: 161, email: 'sam_park@yahoo.com' },
    { name: 'Derek Brown', ident: 162, email: 'derekbrown@gmail.com' },
    { name: 'Lauren Davis', ident: 163, email: 'lauren_davis@yahoo.com' },
    { name: 'Cameron Wright', ident: 164, email: 'cameron_wright@gmail.com' },
    { name: 'Hannah Wilson', ident: 165, email: 'hannahwils@hotmail.com' },
    { name: 'Leo Chen', ident: 166, email: 'leochen@gmail.com' },
    { name: 'Maya Perez', ident: 167, email: 'mayaperez@hotmail.com' },
    { name: 'Oscar Garcia', ident: 168, email: 'oscar_garcia@gmail.com' },
    { name: 'Zoe Scott', ident: 169, email: 'zoe_scott@yahoo.com' },
    { name: 'Max Johnson', ident: 170, email: 'max_johnson@gmail.com' },
    { name: 'Avery Taylor', ident: 171, email: 'averytaylor@hotmail.com' },
    { name: 'Luke Hill', ident: 172, email: 'luke_hill@gmail.com' },
    { name: 'Ella Martin', ident: 173, email: 'ellamartin@yahoo.com' },
    { name: 'Miles Mitchell', ident: 174, email: 'mitchell_miles@gmail.com' },
    { name: 'Amelia Turner', ident: 175, email: 'ameliaturner@hotmail.com' },
    { name: 'Nicholas Adams', ident: 176, email: 'nick_adams@gmail.com' },
    { name: 'Scarlett Baker', ident: 177, email: 'scarlett_baker@yahoo.com' },
    { name: 'Ethan Nelson', ident: 178, email: 'ethan_nelson@gmail.com' },
    { name: 'Abigail Clark', ident: 179, email: 'abigailclark@hotmail.com' },
    { name: 'Sebastian Hernandez', ident: 180, email: 'sebastian_hernandez@gmail.com' },
    { name: 'Addison King', ident: 181, email: 'addison_king@hotmail.com' },
    { name: 'Lucas Walker', ident: 182, email: 'lucas_walker@gmail.com' },
    { name: 'Chloe Baker', ident: 183, email: 'chloebaker@yahoo.com' },
    { name: 'Alexander Young', ident: 184, email: 'alex_young@gmail.com' },
    { name: 'Violet Lee', ident: 185, email: 'violet_lee@hotmail.com' },
    { name: 'Gabriel Lee', ident: 186, email: 'gabe_lee@gmail.com' },
    { name: 'Sophie Chen', ident: 187, email: 'sophiechen@mail.com'},
    { name: 'Emily Liu', ident: 188, email: 'emilyliu@mail.com'},
    { name: 'Grace Lin', ident: 189, email: 'gracelin@mail.com'},
    { name: 'Lucas Wong', ident: 190, email: 'lucaswong@mail.com'},
    { name: 'Alexa Young', ident: 191, email: 'alexayoung@mail.com'},
    { name: 'Oliver Kim', ident: 192, email: 'oliverkim@mail.com'},
    { name: 'Mia Nguyen', ident: 193, email: 'mianguyen@mail.com'},
    { name: 'Sophie Patel', ident: 194, email: 'sophiepatel@mail.com'},
    { name: 'Evelyn Kim', ident: 195, email: 'evelynkim@mail.com'},
    { name: 'Zachary Nguyen', ident: 196, email: 'zacharynguyen@mail.com'},
    { name: 'Chloe Kim', ident: 197, email: 'chloekim@mail.com'},
    { name: 'Avery Park', ident: 198, email: 'averypark@mail.com'},
    { name: 'Nathan Chen', ident: 199, email: 'nathanchen@mail.com'},
    { name: 'Isabella Kim', ident: 200, email: 'isabellakim@mail.com'},
    { name: 'Nicholas Park', ident: 201, email: 'nicholaspark@mail.com'},
    { name: 'Aaliyah Lee', ident: 202, email: 'aaliyahlee@mail.com'},
    { name: 'Leah Park', ident: 203, email: 'leahpark@mail.com'},
    { name: 'Aaron Lee', ident: 204, email: 'aaronlee@mail.com'},
    { name: 'Vivian Chen', ident: 205, email: 'vivianchen@mail.com'},
    { name: 'Andrew Kim', ident: 206, email: 'andrewkim@mail.com'},
    { name: 'Abigail Lee', ident: 207, email: 'abigaille@mail.com'},
    { name: 'Samantha Park', ident: 208, email: 'samanthapark@mail.com'},
    { name: 'Jacob Nguyen', ident: 209, email: 'jacobnguyen@mail.com'},
    { name: 'Kaylee Kim', ident: 210, email: 'kayleekim@mail.com'},
    { name: 'Henry Lee', ident: 211, email: 'henrylee@mail.com'},
    { name: 'Audrey Chen', ident: 212, email: 'audreychen@mail.com'},
    { name: 'Brandon Kim', ident: 213, email: 'brandonkim@mail.com'},
    { name: 'Ella Park', ident: 214, email: 'ellapark@mail.com'},
    { name: 'Anthony Lee', ident: 215, email: 'anthonylee@mail.com'},
    { name: 'Elizabeth Kim', ident: 216, email: 'elizabethkim@mail.com'},
    { name: null, ident: 1000, email: 'admin.secure@rode.com'},
  ];

  let output = '';
  if(searchTerm.includes('`OR 1=1') ||searchTerm.includes('` OR 1=1')||searchTerm.includes('OR 1=1')){
    for (let i = 0; i < results.length; i++) {
        if(results[i].name === null){
            output += `<tr><td> null </td><td>${results[i].ident}</td><td>${results[i].email}</td></tr>`;
        }else{
            output += `<tr><td>${results[i].name}</td><td>${results[i].ident}</td><td>${results[i].email}</td></tr>`; 
        }
        
      }
  }else{
    for (let i = 0; i < results.length; i++) {
        if(results[i].name != null && results[i].name.includes(searchTerm)){
            output += `<tr><td>${results[i].name}</td><td>${results[i].ident}</td><td>${results[i].email}</td></tr>`;
        }
      }
  }
  


  searchResults.innerHTML = output;
});